#!/bin/bash

wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/adi.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/amoeba.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/anneal.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/avevar.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/badluk.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/balanc.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/bcucof.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/bcuint.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/bessi.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/bessi0.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/bessi1.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/bessj.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/bessj0.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/bessj1.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/bessk.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/bessk0.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/bessk1.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/bessy.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/bessy0.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/bessy1.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/beta.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/betacf.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/betai.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/bico.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/bksub.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/bnldev.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/brent.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/bsstep.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/caldat.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/cel.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/chder.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/chebev.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/chebft.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/chebpc.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/chint.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/chsone.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/chstwo.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/cntab1.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/cntab2.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/complex.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/convlv.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/correl.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/cosft.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/covsrt.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/crank.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/dbrent.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/ddpoly.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/des.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/desks.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/df1dim.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/dfpmin.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/difeq.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/dlinmin.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/eclass.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/eclazz.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/eigsrt.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/el2.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/elmhes.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/erf.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/erfc.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/erfcc.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/eulsum.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/evlmem.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/expdev.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/f1dim.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/factln.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/factrl.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/fgauss.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/fit.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/fixrts.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/fleg.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/flmoon.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/four1.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/fourn.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/fpoly.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/frprmn.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/ftest.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/gamdev.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/gammln.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/gammp.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/gammq.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/gasdev.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/gauleg.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/gaussj.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/gcf.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/golden.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/gser.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/hqr.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/hunt.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/indexx.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/irbit1.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/irbit2.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/jacobi.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/julday.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/kendl1.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/kendl2.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/ksone.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/kstwo.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/laguer.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/lfit.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/linmin.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/locate.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/lubksb.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/ludcmp.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/mdian1.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/mdian2.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/medfit.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/memcof.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/midexp.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/midinf.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/midpnt.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/midsql.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/midsqu.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/mmid.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/mnbrak.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/mnewt.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/moment.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/mprove.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/mrqcof.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/mrqmin.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/nrutil.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/odeint.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/pcshft.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/pearsn.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/piksr2.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/piksrt.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/pinvs.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/plgndr.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/poidev.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/polcoe.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/polcof.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/poldiv.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/polin2.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/polint.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/powell.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/predic.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/probks.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/pzextr.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/qcksrt.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/qgaus.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/qromb.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/qromo.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/qroot.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/qsimp.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/qtrap.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/quad3d.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/ran0.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/ran1.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/ran2.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/ran3.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/ran4.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/rank.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/ratint.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/realft.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/red.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/rk4.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/rkdumb.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/rkqc.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/rofunc.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/rtbis.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/rtflsp.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/rtnewt.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/rtsafe.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/rtsec.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/rzextr.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/scrsho.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/sfroid.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/shell.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/shoot.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/shootf.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/simp1.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/simp2.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/simp3.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/simplx.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/sinft.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/smooft.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/sncndn.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/solvde.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/sor.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/sort.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/sort2.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/sort3.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/sparse.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/spctrm.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/spear.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/splie2.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/splin2.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/spline.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/splint.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/svbksb.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/svdcmp.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/svdfit.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/svdvar.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/toeplz.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/tptest.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/tqli.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/trapzd.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/tred2.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/tridag.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/ttest.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/tutest.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/twofft.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/vander.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/zbrac.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/zbrak.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/zbrent.c
wget http://ftp.cs.stanford.edu/cs/robotics/scohen/nr/zroots.c

exit 0